### ISSUE TITLE
Assignment 2 is ready for review!

### ISSUE THREAD

**Issue by r-cadena** [VIS-2129-F2020/rogeliocadena-vis#2]
Good evening, 
I have added the .html and .rmd files for Assignment 2. Please find the html url below. I hope you like it!
https://vis-2129-f2020.github.io/rogeliocadena-vis/Assignment-2

**Comment by bauranov** [comment]
Very nice work, aesthetically very appealing! Consider adding names of the states/provinces to the map. Looking forward to your next assignment.
