### ISSUE TITLE
Assignment 3 is ready for review!

### ISSUE THREAD

**Issue by r-cadena** [VIS-2129-F2020/rogeliocadena-vis#3]
I have added Assignment 3 .html and .rmd files. I hope you like them!

Please see the html link below:
https://vis-2129-f2020.github.io/rogeliocadena-vis/Assignment-3

To note: Aleksander helped me create an up close map of the Central business district (Map 2) in order to locate the high ranging variable in the dataset. If the map was represented any further it would have been difficult to read this outline variable.

**Comment by bauranov** [comment]
Great work!
