### ISSUE TITLE
Assignment 4 is ready for review

### ISSUE THREAD

**Issue by r-cadena** [VIS-2129-F2020/rogeliocadena-vis#4]
I have spoken to Taelor and have sent her the .rmd file as I have been unable to push the file gethub for some reason or another. I hope you like the graphs and maps nonetheless!

**Comment by traemalcolm** [comment]
I was actually able to push the file from my computer. Here's the link:

https://vis-2129-f2020.github.io/rogeliocadena-vis/Assignment4.html

**Comment by bauranov** [comment]
Good work. Make sure to review your html before submission and remove all unwanted messages and warnings.
